# Generated by Django 5.0.1 on 2026-02-01 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("all_offices", models.BooleanField(default=True)),
                ("can_complete", models.BooleanField(default=True)),
                ("can_return", models.BooleanField(default=True)),
                ("can_sign", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "delegate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specific_offices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="delegations",
                        to="organizations.office",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["delegator", "is_active"],
                        name="accounts_de_delegat_4263ce_idx",
                    ),
                    models.Index(
                        fields=["delegate", "is_active"],
                        name="accounts_de_delegat_5edc91_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="accounts_de_start_d_9e45f8_idx",
                    ),
                ],
            },
        ),
    ]
