# Generated by Django 5.2.10 on 2026-01-31 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("packages", "0002_tab_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "node_type",
                    models.CharField(
                        choices=[("stage", "Stage"), ("action", "Action")],
                        max_length=20,
                    ),
                ),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("send_alert", "Send Alert"),
                            ("send_email", "Send Email"),
                            ("complete", "Complete Workflow"),
                            ("reject", "Reject Workflow"),
                            ("wait", "Wait"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("inline", "Inline (Blocking)"),
                            ("forked", "Forked (Parallel)"),
                        ],
                        default="inline",
                        max_length=10,
                    ),
                ),
                ("action_config", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="NodeConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_node", models.CharField(max_length=50)),
                ("to_node", models.CharField(max_length=50)),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("default", "Default Path"),
                            ("return", "Return Path"),
                            ("reject", "Reject Path"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StageNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "node_type",
                    models.CharField(
                        choices=[("stage", "Stage"), ("action", "Action")],
                        max_length=20,
                    ),
                ),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("REVIEW", "Review"),
                            ("APPROVE", "Approve"),
                            ("SIGN", "Sign"),
                            ("ACCEPT", "Accept"),
                            ("COORD", "Coordinate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "multi_office_rule",
                    models.CharField(
                        choices=[
                            ("any", "Any office can complete"),
                            ("all", "All offices must complete"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                ("timeout_days", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="workflowtemplate",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="canvas_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Drawflow export data for visual rendering",
            ),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_workflow_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="workflowtemplate",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="workflowtemplate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for shared templates available to all organizations",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_templates",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["organization", "is_active"],
                name="packages_wo_organiz_3a364d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["created_by"], name="packages_wo_created_ba367a_idx"
            ),
        ),
        migrations.AddField(
            model_name="actionnode",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_nodes",
                to="packages.workflowtemplate",
            ),
        ),
        migrations.AddField(
            model_name="nodeconnection",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections",
                to="packages.workflowtemplate",
            ),
        ),
        migrations.AddField(
            model_name="stagenode",
            name="assigned_offices",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_stage_nodes",
                to="organizations.office",
            ),
        ),
        migrations.AddField(
            model_name="stagenode",
            name="escalation_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalation_stage_nodes",
                to="organizations.office",
            ),
        ),
        migrations.AddField(
            model_name="stagenode",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_nodes",
                to="packages.workflowtemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="actionnode",
            index=models.Index(
                fields=["template", "action_type"],
                name="packages_ac_templat_a72d9b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="actionnode",
            unique_together={("template", "node_id")},
        ),
        migrations.AddIndex(
            model_name="nodeconnection",
            index=models.Index(
                fields=["template", "from_node"], name="packages_no_templat_13cabb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeconnection",
            index=models.Index(
                fields=["template", "to_node"], name="packages_no_templat_9eeb31_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nodeconnection",
            unique_together={("template", "from_node", "to_node", "connection_type")},
        ),
        migrations.AddIndex(
            model_name="stagenode",
            index=models.Index(
                fields=["template", "action_type"],
                name="packages_st_templat_73f200_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stagenode",
            unique_together={("template", "node_id")},
        ),
    ]
