# Generated by Django 5.2.10 on 2026-01-31 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("packages", "0003_actionnode_nodeconnection_stagenode_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StageAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node_id", models.CharField(max_length=50)),
                ("actor_position", models.CharField(blank=True, max_length=200)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("return", "Return"),
                            ("reject", "Reject"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("return_to_node", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stage_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "actor_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stage_actions",
                        to="organizations.office",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_actions",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoutingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_node", models.CharField(blank=True, max_length=50)),
                ("to_node", models.CharField(max_length=50)),
                (
                    "transition_type",
                    models.CharField(
                        choices=[
                            ("submit", "Submitted to Routing"),
                            ("advance", "Advanced to Next Stage"),
                            ("return", "Returned to Previous Stage"),
                            ("reject", "Rejected"),
                            ("complete", "Workflow Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_history",
                        to="packages.package",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_transitions",
                        to="packages.stageaction",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Routing histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StageCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node_id", models.CharField(max_length=50)),
                (
                    "completed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_completion",
                        to="packages.stageaction",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stage_completions",
                        to="organizations.office",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_completions",
                        to="packages.package",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="stageaction",
            index=models.Index(
                fields=["package", "node_id"], name="packages_st_package_e87bb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stageaction",
            index=models.Index(fields=["actor"], name="packages_st_actor_i_441cb1_idx"),
        ),
        migrations.AddIndex(
            model_name="routinghistory",
            index=models.Index(
                fields=["package", "-created_at"], name="packages_ro_package_f10f2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stagecompletion",
            index=models.Index(
                fields=["package", "node_id"], name="packages_st_package_05e984_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stagecompletion",
            unique_together={("package", "node_id", "office")},
        ),
    ]
