# Generated by Django 5.2.10 on 2026-02-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0004_stageaction_routinghistory_stagecompletion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stagenode",
            name="multi_office_rule",
        ),
        migrations.AlterField(
            model_name="stagenode",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("APPROVE", "Approve"),
                    ("COORD", "Coordinate"),
                    ("CONCUR", "Concur"),
                ],
                max_length=20,
            ),
        ),
    ]
