# Generated by Django 5.0.1 on 2026-02-01 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("packages", "0005_remove_stagenode_multi_office_rule_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("signer_name", models.CharField(max_length=255)),
                ("signer_email", models.EmailField(max_length=254)),
                ("signer_position", models.CharField(max_length=255)),
                (
                    "signature_type",
                    models.CharField(
                        choices=[
                            ("CONCUR", "Concur"),
                            ("APPROVE", "Approve"),
                            ("CERTIFY", "Certify"),
                            ("ACKNOWLEDGE", "Acknowledge"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("x509", "X.509 Certificate"), ("pgp", "PGP Key")],
                        max_length=10,
                    ),
                ),
                ("key_fingerprint", models.CharField(max_length=64)),
                ("canonical_payload", models.TextField()),
                ("signature_blob", models.BinaryField()),
                ("certificate_snapshot", models.BinaryField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("expired", "Expired"),
                            ("invalid", "Invalid"),
                            ("revoked", "Revoked"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signer_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatures",
                        to="organizations.office",
                    ),
                ),
                (
                    "stage_action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature",
                        to="packages.stageaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrityViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("change_reason", models.TextField()),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("acknowledged", "Acknowledged"),
                            ("reset", "Routing Reset"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_violations",
                        to="packages.package",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caused_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "violating_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="packages.document",
                    ),
                ),
                (
                    "affected_signatures",
                    models.ManyToManyField(
                        related_name="violations", to="packages.signature"
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="signature",
            index=models.Index(
                fields=["signer"], name="packages_si_signer__e24ff0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signature",
            index=models.Index(
                fields=["verification_status"], name="packages_si_verific_0187e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrityviolation",
            index=models.Index(
                fields=["package", "resolution"], name="packages_in_package_f120d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrityviolation",
            index=models.Index(
                fields=["detected_at"], name="packages_in_detecte_2aa39c_idx"
            ),
        ),
    ]
