# Generated by Django 5.2.10 on 2026-02-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0006_signature_and_integrity_violation"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagenode",
            name="multi_office_rule",
            field=models.CharField(
                choices=[
                    ("any", "Any (first completion advances)"),
                    ("all", "All (all offices must complete)"),
                ],
                default="any",
                help_text="When multiple offices are assigned: 'any' advances on first completion, 'all' waits for all",
                max_length=10,
            ),
        ),
    ]
