# Generated by Django 5.2.10 on 2026-02-06 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_add_contact_fields"),
        ("packages", "0007_add_multi_office_rule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageActionRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("user", "Specific User"),
                            ("office", "All Office Members"),
                            ("email", "Email Address"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                (
                    "action_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_recipients",
                        to="packages.actionnode",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_recipient_assignments",
                        to="organizations.office",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_recipients",
                        to="packages.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_recipient_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["package", "action_node"],
                        name="packages_pa_package_6febda_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PackageStageAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offices",
                    models.ManyToManyField(
                        related_name="package_stage_assignments",
                        to="organizations.office",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_assignments",
                        to="packages.package",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_assignments",
                        to="packages.stagenode",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["package", "stage"],
                        name="packages_pa_package_d1b3b9_idx",
                    )
                ],
                "unique_together": {("package", "stage")},
            },
        ),
    ]
