# Generated by Django 5.2.10 on 2026-01-31 15:04

from django.db import migrations


def create_default_settings(apps, schema_editor):
    SystemSetting = apps.get_model('core', 'SystemSetting')
    defaults = [
        ('brand_name', 'Papertrail', 'Application display name', 'branding'),
        ('brand_logo_url', '', 'URL to logo image (optional)', 'branding'),
        ('brand_favicon_url', '', 'URL to favicon (optional)', 'branding'),
        ('brand_primary_color', '#2563eb', 'Primary brand color (hex)', 'branding'),
        ('brand_accent_color', '#1d4ed8', 'Accent/hover color (hex)', 'branding'),
        ('support_email', '', 'Support email address', 'branding'),
        ('support_url', '', 'Support/help URL', 'branding'),
        ('login_banner_text', '', 'Banner text shown on login page', 'branding'),
        ('footer_text', '', 'Footer text', 'branding'),
    ]
    for key, value, desc, cat in defaults:
        SystemSetting.objects.get_or_create(
            key=key,
            defaults={'value': value, 'description': desc, 'category': cat}
        )


def remove_default_settings(apps, schema_editor):
    SystemSetting = apps.get_model('core', 'SystemSetting')
    SystemSetting.objects.filter(category='branding').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_settings, remove_default_settings),
    ]
