"""Management command to generate Django environment keys."""

import secrets
import string
from pathlib import Path

from django.core.management.base import BaseCommand
from django.core.management.utils import get_random_secret_key


class Command(BaseCommand):
    help = "Generate Django environment keys (SECRET_KEY, etc.) and optionally write to .env file"

    def add_arguments(self, parser):
        parser.add_argument(
            "--output",
            "-o",
            type=str,
            help="Output file path (default: prints to stdout)",
        )
        parser.add_argument(
            "--append",
            "-a",
            action="store_true",
            help="Append to existing file instead of overwriting",
        )
        parser.add_argument(
            "--env-file",
            action="store_true",
            help="Create/update .env file in project root",
        )
        parser.add_argument(
            "--include-debug",
            action="store_true",
            help="Include DEBUG=True setting (for development)",
        )
        parser.add_argument(
            "--database-url",
            type=str,
            help="Database URL to include (default: sqlite for dev)",
        )

    def generate_secret_key(self):
        """Generate a Django-compatible secret key."""
        return get_random_secret_key()

    def generate_database_key(self, length=32):
        """Generate a secure key for database encryption."""
        alphabet = string.ascii_letters + string.digits
        return "".join(secrets.choice(alphabet) for _ in range(length))

    def generate_api_key(self, prefix="pk_", length=32):
        """Generate an API key with optional prefix."""
        alphabet = string.ascii_letters + string.digits
        return prefix + "".join(secrets.choice(alphabet) for _ in range(length))

    def handle(self, *args, **options):
        # Generate all keys
        secret_key = self.generate_secret_key()
        db_encryption_key = self.generate_database_key()
        internal_api_key = self.generate_api_key(prefix="int_")

        # Build environment content
        lines = [
            "# Django Settings",
            "# Generated by: python manage.py generate_env_keys",
            "",
            f"SECRET_KEY={secret_key}",
            "",
        ]

        if options["include_debug"]:
            lines.extend([
                "# Debug mode (set to False in production!)",
                "DEBUG=True",
                "",
            ])

        # Database URL
        if options["database_url"]:
            lines.extend([
                "# Database",
                f"DATABASE_URL={options['database_url']}",
                "",
            ])
        else:
            lines.extend([
                "# Database (uncomment and configure for production)",
                "# DATABASE_URL=postgres://user:password@localhost:5432/papertrail",
                "",
            ])

        # Additional security keys
        lines.extend([
            "# Database Field Encryption Key (for sensitive data)",
            f"DB_ENCRYPTION_KEY={db_encryption_key}",
            "",
            "# Internal API Key (for service-to-service communication)",
            f"INTERNAL_API_KEY={internal_api_key}",
            "",
            "# Email settings (configure for production)",
            "# EMAIL_HOST=smtp.example.com",
            "# EMAIL_PORT=587",
            "# EMAIL_USE_TLS=True",
            "# EMAIL_HOST_USER=your-email@example.com",
            "# EMAIL_HOST_PASSWORD=your-email-password",
            "# DEFAULT_FROM_EMAIL=noreply@example.com",
            "",
            "# Allowed hosts (configure for production)",
            "# ALLOWED_HOSTS=example.com,www.example.com",
            "",
        ])

        content = "\n".join(lines)

        # Determine output destination
        output_path = None
        if options["env_file"]:
            # Use project root .env
            output_path = Path(__file__).resolve().parents[4] / ".env"
        elif options["output"]:
            output_path = Path(options["output"])

        if output_path:
            mode = "a" if options["append"] else "w"

            if output_path.exists() and not options["append"]:
                self.stdout.write(
                    self.style.WARNING(f"File {output_path} already exists!")
                )
                self.stdout.write("Use --append to add to existing file, or delete it first.")
                self.stdout.write("")
                self.stdout.write("Generated keys (copy manually if needed):")
                self.stdout.write("-" * 50)

            with open(output_path, mode) as f:
                if options["append"]:
                    f.write("\n")  # Add separator from existing content
                f.write(content)

            self.stdout.write(
                self.style.SUCCESS(f"{'Appended to' if options['append'] else 'Wrote'} {output_path}")
            )
        else:
            # Print to stdout
            self.stdout.write(self.style.SUCCESS("Generated Environment Keys:"))
            self.stdout.write("-" * 50)

        # Always show the keys that were generated
        self.stdout.write(content)

        self.stdout.write("-" * 50)
        self.stdout.write(
            self.style.WARNING(
                "⚠️  Keep these keys secure! Never commit them to version control."
            )
        )
