# Generated by Django 5.2.10 on 2026-02-01 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_simplify_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="officemembership",
            options={"ordering": ["-joined_at"]},
        ),
        migrations.RenameIndex(
            model_name="office",
            new_name="organizatio_parent__f153a0_idx",
            old_name="organizatio_parent__9ac4b4_idx",
        ),
        migrations.RenameIndex(
            model_name="officemembership",
            new_name="organizatio_role_75631f_idx",
            old_name="organizatio_role_7c0254_idx",
        ),
        migrations.AlterField(
            model_name="office",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="organizations.office",
            ),
        ),
    ]
