# Generated by Django 5.2.10 on 2026-02-05 00:50

from django.db import migrations, models


def rename_admin_to_manager(apps, schema_editor):
    """Update role values from admin to manager."""
    OrganizationMembership = apps.get_model("organizations", "OrganizationMembership")
    OfficeMembership = apps.get_model("organizations", "OfficeMembership")

    # Update org_admin -> org_manager
    OrganizationMembership.objects.filter(role="org_admin").update(role="org_manager")

    # Update admin -> manager
    OfficeMembership.objects.filter(role="admin").update(role="manager")


def rename_manager_to_admin(apps, schema_editor):
    """Reverse: Update role values from manager back to admin."""
    OrganizationMembership = apps.get_model("organizations", "OrganizationMembership")
    OfficeMembership = apps.get_model("organizations", "OfficeMembership")

    # Update org_manager -> org_admin
    OrganizationMembership.objects.filter(role="org_manager").update(role="org_admin")

    # Update manager -> admin
    OfficeMembership.objects.filter(role="manager").update(role="admin")


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_align_model_options"),
    ]

    operations = [
        # First, update the data
        migrations.RunPython(rename_admin_to_manager, rename_manager_to_admin),
        # Then, update the field choices
        migrations.AlterField(
            model_name="officemembership",
            name="role",
            field=models.CharField(
                choices=[("manager", "Manager"), ("member", "Member")],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("org_manager", "Organization Manager"),
                    ("org_member", "Organization Member"),
                ],
                default="org_member",
                max_length=20,
            ),
        ),
    ]
