# Generated by Django 5.2.10 on 2026-02-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_add_status_to_officemembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="General contact email for this office",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="office",
            name="contact_phone",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="General contact email for this organization",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_phone",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=30
            ),
        ),
    ]
